#!/usr/bin/python
#
# find-provides: munge the provides dependencies from the kabideps file
#
# This software may be freely redistributed under the terms of the GNU
# General Public License (GPL).
#
# Takes a directory prefix, then outputs the kernel ABI dependencies.

__author__ = "Jon Masters <jcm@redhat.com>"
__version__ = "3.0"
__date__ = "Sun 16 Dec 2012 05:00 EST"
__copyright__ = "Copyright (C) 2009 Red Hat, Inc"
__license__ = "GPL"

import os
import re
import string
import sys
from subprocess import Popen, PIPE

false = 0
true = 1

kabideps=""

input = sys.stdin.readlines()

p = re.compile('^(.*)/symvers-(.*).gz$')
for line in input:
	if input == "":
		break
	string.split(line)
	m = p.match(line)
	if m:
		kabideps=sys.argv[1] + "/kernel-" + m.group(2) + "-kabideps"

if kabideps == "":
	p = Popen(["/usr/lib/rpm/redhat/find-provides", "kernel"], stdin=PIPE, stdout=PIPE)
	for line in input:
		string.split(line)
		p.stdin.write(line)
	p.stdin.close()
	for dep in p.stdout.readlines():
		sys.stdout.write(dep)
	sys.exit(0)

if not (os.path.isfile(kabideps)):
	sys.stderr.write(sys.argv[0] + ": cannot locate kabideps file: " + kabideps + "\n")
	sys.exit(1)

sys.stderr.write(sys.argv[0] + ": processing kABI: " + kabideps + "\n")
os.system("cat " + kabideps)
