#!/usr/bin/python
#
# make-kabi - Red Hat kABI reference module generation tool
#
# We use this script to generate reference Module.kabi files.
#
# Author: Jon Masters <jcm@redhat.com>
# Copyright (C) 2007 Red Hat, Inc.
#
# This software may be freely redistributed under the terms of the GNU
# General Public License (GPL).

# Changelog:
# 
# 2007/06/13 - Initial rewrite in python by Jon Masters.

__author__ = "Jon Masters <jcm@redhat.com>"
__version__ = "1.0"
__date__ = "2007/06/13"
__copyright__ = "Copyright (C) 2007 Red Hat, Inc"
__license__ = "GPL"

import getopt
import os
import re
import sha
import string
import sys

true = 1
false = 0

def load_symvers(symvers,filename):
	"""Load a reference Module.symvers file."""

	symvers_file = open(filename,"r")

	while true:
		in_line = symvers_file.readline()
		if in_line == "":
			break
		if in_line == "\n":
			continue
		checksum,symbol,directory,type = string.split(in_line)

		symvers[symbol] = in_line[0:-1]

def load_whitelist(whitelist,filename):
	"""Load a reference whitelist file."""

	whitelist_file = open(filename,"r")

	while true:
		in_line = whitelist_file.readline()
		if in_line == "":
			break
		if in_line == "\n":
			continue
		string.split(in_line)
		if in_line[0] == "[":
			continue
		symbol = in_line[1:-1]

		whitelist.append(symbol)

	whitelist.sort()

def make_kabi(filename,symvers,whitelist):
	"""Munge together whitelist and Module.symvers file."""

	kabi = []

	if os.path.isfile(filename):
		print filename + " already exists"
		sys.exit(1)

	kabi_file = open(filename,"w")

	for symbol in whitelist:
		if symvers.has_key(symbol):
			kabi_file.write(symvers[symbol] + "\n")

def usage():
	print """
make-kabi: process Module.symvers into reference Module.kabi output file using
          the kabi_whitelist file provided as a set of symbols to filer on.

	make-kabi [ -k Module.kabi ] [ -s Module.symvers ] [ -w kabi_whitelist ]

"""

if __name__ == "__main__":

	whitelist_file = ""
	symvers_file = ""
	kabi_file = ""

	opts, args = getopt.getopt(sys.argv[1:], 'hk:s:w:')

	for o, v in opts:
		if o == "-s":
			symvers_file = v
		if o == "-h":
			usage()
			sys.exit(0)
		if o == "-k":
			kabi_file = v
		if o == "-w":
			whitelist_file = v
	
	if (whitelist_file == "") or (symvers_file == "") or (kabi_file == ""):
		usage()
		sys.exit(1)

	symvers={}
	whitelist=[]

	load_symvers(symvers,symvers_file)
	load_whitelist(whitelist,whitelist_file)
	make_kabi(kabi_file,symvers,whitelist)
